-- Notação mínima de matemática discreta (ctx-source: usando-matematica-discreta-no-meu-dia-a-dia)
-- Gatilhos em sintaxe LaTeX (padrão reconhecido por qualquer agente/matemático),
-- expandem direto pro símbolo Unicode ao digitar espaço/pontuação — sem $...$, sem toolchain.
-- '\' precisa contar como keyword char pro parser de :iabbrev aceitar lhs tipo "\forall"
-- (senão é E474: nem full-id nem end-id nem non-id — ver :help abbreviations).
vim.opt_local.iskeyword:append('92')

local function iab(lhs, rhs) vim.cmd(string.format('iabbrev <buffer> %s %s', lhs, rhs)) end

iab([[\in]], '∈')
iab([[\notin]], '∉')
iab([[\subseteq]], '⊆')
iab([[\subset]], '⊂')
iab([[\cup]], '∪')
iab([[\cap]], '∩')
iab([[\setminus]], '<Bslash>')
iab([[\emptyset]], '∅')
iab([[\forall]], '∀')
iab([[\exists]], '∃')
iab([[\to]], '→')
iab([[\iff]], '↔')
iab([[\neg]], '¬')
iab([[\land]], '∧')
iab([[\lor]], '∨')
iab([[\mid]], '<Bar>')
iab([[\times]], '×')
iab([[\sqsubseteq]], '⊑')
iab([[\models]], '⊨')
iab([[\vdash]], '⊢')
iab([[\equiv]], '≡')
iab([[\neq]], '≠')
iab([[\leq]], '≤')
iab([[\geq]], '≥')
iab([[\N]], 'ℕ')
iab([[\Z]], 'ℤ')
iab([[\R]], 'ℝ')
iab([[\U]], '𝕌')
iab([[\fn]], '𝑓')
iab([[\Rightarrow]], '⇒')
iab([[\Leftrightarrow]], '⇔')
iab([[\:=]], '≔')
iab([[\aleph]], 'ℵ')
iab([[\bigcap]], '⋂')
iab([[\bigcup]], '⋃')
iab([[\infty]], '∞')
iab([[\circ]], '∘')
iab([[\top]], '⊤')
iab([[\bot]], '⊥')
iab([[\cdot]], '·')
iab([[\powerset]], '𝒫')
iab([[\uplus]], '⊎')
iab([[\ominus]], '⊖')
iab([[\lambda]], 'λ')
iab([[\epsilon]], 'ε')
iab([[\Sigma]], 'Σ')
iab([[\Pi]], 'Π')
iab([[\alpha]], 'α')
iab([[\beta]], 'β')
iab([[\gamma]], 'γ')
iab([[\delta]], 'δ')
iab([[\Delta]], 'Δ')
